[project]
name = "Iris"
version = "1.1.1"
description = "Centralisateur d'api"
mainfile = "app.py"
requires-python = ">=3.13"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "mit"
license_file = "LICENSE"
keywords = []
classifiers = []
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = ""
documentation = ""

[project.dependencies]
flask = "N.A"
zpp_store = "N.A"
werkzeug = "N.A"
pyjwt = "N.A"
zpp_color = "N.A"
flask_sqlalchemy = "N.A"
SQLAlchemy = "N.A"
pyyaml = "N.A"
requests = "N.A"
pycryptodome = "N.A"
cryptography = "N.A"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["os", "datetime", "time", "logging", "functools", "hashlib", "secrets", "uuid", "sys", "re", "ipaddress", "ast", "importlib", "inspect", "json", "flask", "zpp_store", "werkzeug", "pyjwt", "yaml", "zpp_color", "flask_sqlalchemy"]
includes = ["core", "models", "views"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []

[venv.runner]
env_dir = ".venv/runner"
env_name = "runner"
env_exe = ".venv/runner/Scripts/python.exe"
bin_path = ".venv/runner/Scripts"
version = "N.A"
default = true
