server:
  host: 127.0.0.1
  port: 5000

  template_dir: templates
  static_dir: static


secret_key: your_super_secret_key_here

app:
  mode: dev

  debug: False

  auth: True
  admin: True
  home: True

auto_protect:
  enable: True
  blacklist: "null"
  whitelist: "null"
  max_fail: 5
  fail_interval: 300
  ban_time: 300

database:
  engine: sqlite
  filename: app.db